### ISSUE TITLE
Generator 'MapperGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result.

### ISSUE THREAD

**Issue by alexandrucatalinene** [riok/mapperly#1403]
**Describe the bug**
I have a very simple mapping made from a model to a dto but it seems it doesn't work. I get this error in the console (Visual Studio 2022)
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning (active)	CS8785	Generator 'MapperGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Collection was modified; enumeration operation may not execute.'.	Api Path\CSC	1	
```

The code gets generated but it's not included in the build so it gives an error.

**Declaration code**
```csharp
// Relevant code of the Mapperly definition and all relevant classes
[Mapper]
public static partial class UserMapper
{
	public static partial User MapDtoToDb(UserDTO user);
	public static partial UserDTO MapDbToDto(User user);
}

public class UserDTO
{
	public int Id { get; set; }
	public string? Name { get; set; }
	public string? DeviceId { get; set; }
	public string? Password { get; set; }
}
```

**Actual relevant generated code**
```csharp
// Actual relevant code generated by Mapperly
// see also https://mapperly.riok.app/docs/configuration/generated-source/
```

**Expected relevant generated code**
```csharp
// The generated code how you expect it to look like
public static partial class UserMapper
{
	[global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.0.0.0")]
	public static global::Api.Database.Models.User MapDtoToDb(global::Api.DTO.UserDTO user)
	{
		var target = new global::Api.Database.Models.User()
		{
			Name = user.Name ?? "",
			DeviceId = user.DeviceId ?? "",
			Password = user.Password ?? "",
		};
		target.Id = user.Id;
		return target;
	}

	[global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.0.0.0")]
	public static global::Api.DTO.UserDTO MapDbToDto(global::Api.Database.Models.User user)
	{
		var target = new global::Api.DTO.UserDTO();
		target.Id = user.Id;
		target.Name = user.Name;
		target.DeviceId = user.DeviceId;
		target.Password = user.Password;
		return target;
	}
}
```

**Environment (please complete the following information):**
- Mapperly Version: [4.0.0.0] :
- Nullable reference types: [enabled] 
- .NET Version: [dotnet 8.0] 
- Target Framework: [e.g. .net8.0]
- Compiler Version: [4.10.0-3.24324.8 (0dfb3916)]
- C# Language Version: [12.0]
- IDE: [v17.10.4]
- OS: [Win 10]

**Additional context**
Simple dotnet minimap API project.

**Comment by latonz** [comment]
Thanks for reporting. Could you post the source of your `User` class?

**Comment by alexandrucatalinene** [comment]
Sure. Sorry for the late reply

```
public class User
{
	public int Id { get; set; }
	public required string Name { get; set; }
	public required string DeviceId { get; set; }
	public required string Password { get; set; }
}
```

**Comment by alexandrucatalinene** [comment]
I also managed to obtained a stacktrace of the error

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Riok.Mapperly.Descriptors.MappingBodyBuilders.ObjectMemberMappingBodyBuilder.BuildMappingBody(IMembersContainerBuilderContext`1 ctx) in /_/src/Riok.Mapperly/Descriptors/MappingBodyBuilders/ObjectMemberMappingBodyBuilder.cs:line 30
   at Riok.Mapperly.Descriptors.MappingBodyBuilders.NewInstanceObjectMemberMappingBodyBuilder.BuildMappingBody(MappingBuilderContext ctx, NewInstanceObjectMemberMethodMapping mapping) in /_/src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs:line 36
   at Riok.Mapperly.Descriptors.MappingBodyBuilders.MappingBodyBuilder.BuildMappingBodies(CancellationToken cancellationToken) in /_/src/Riok.Mapperly/Descriptors/MappingBodyBuilders/MappingBodyBuilder.cs:line 27
   at Riok.Mapperly.Descriptors.DescriptorBuilder.Build(CancellationToken cancellationToken) in /_/src/Riok.Mapperly/Descriptors/DescriptorBuilder.cs:line 84
   at Riok.Mapperly.MapperGenerator.BuildDescriptor(CompilationContext compilationContext, MapperDeclaration mapperDeclaration, MapperConfiguration mapperDefaults, CancellationToken cancellationToken) in /_/src/Riok.Mapperly/MapperGenerator.cs:line 80
   at Riok.Mapperly.MapperGenerator.<>c.<Initialize>b__2_3(ValueTuple`2 x, CancellationToken ct) in /_/src/Riok.Mapperly/MapperGenerator.cs:line 48
   at Microsoft.CodeAnalysis.UserFunctionExtensions.<>c__DisplayClass0_0`2.<WrapUserFunction>b__0(TInput input, CancellationToken token)
```

**Comment by latonz** [comment]
I cannot reproduce this, do you have any additional configuration? Any mapperly related attributes or properties (e.g. `MapperlyDefaults`)? Could you share a minimal repro as a GitHub repo/gist?

**Comment by alexandrucatalinene** [comment]
Update. I tried it on the same machine but with rider and it works.

**Comment by latonz** [comment]
Does it work on the cli and in docker?

**Comment by alexandrucatalinene** [comment]
It works with cli - didn't try it with docker but it's probably the same since it's also cli.

So, this leads me to believe it has something to do with VS

**Comment by latonz** [comment]
Unfortunately I don‘t have easy access to a windows machine and VS, and therefore cannot reproduce this. Maybe one of the previous comitters with a win machine could look into this @CommonGuy @TimothyMakkison @trejjam 😊

**Comment by trejjam** [comment]
I can try to take a look

**Comment by trejjam** [comment]
I was able to reproduce the issue. It's happening only in VS (tested VS 2022, CLI .NET 8, Rider 2024.1.4).

(screenshots are from Rider, but it's attached debugger from VS)

The state after retrieving the first item from `EnumerateUnmappedOrConfiguredTargetMembers` in the `ObjectMemberMappingBodyBuilder`.`BuildMappingBody`:
![Mapperly-VS_init](https://github.com/user-attachments/assets/77cb101b-c1e4-4f66-8ae1-808a016f44ac)

The state changes after `BuildMemberAssignmentMapping` (`Id` is removed from `_unmappedTargetMemberNames`):
![Mapperly-VS_after-BuildMemberAssignmentMapping](https://github.com/user-attachments/assets/90563299-06a4-4bc6-9bb1-0f1eda28b510)

Exception from the `HashSet.Enumerator.MoveNext`:
![Mapperly-VS_hash-set-next-exception](https://github.com/user-attachments/assets/5e434339-9284-4230-9222-8ee9dc2620e1)

**Comment by trejjam** [comment]
PR fixing the issue: #1438
